import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
const staticRoutesSource = readFileSync(new URL('../../apps/web/src/static-routes.ts', import.meta.url), 'utf8')
const seoSource = readFileSync(new URL('../../apps/web/src/seo.ts', import.meta.url), 'utf8')

test('the canonical /shop product route resolves to product metadata', () => {
  assert.ok(staticRoutesSource.includes('path: `/shop/${product.slug}`'))
  assert.ok(staticRoutesSource.includes('path.match(/^\\/shop\\/([^/]+)$/)'))
  assert.ok(!staticRoutesSource.includes('path.match(/^\\/product\\/'))
  assert.match(seoSource, /'@type': 'BreadcrumbList'/)
  assert.match(seoSource, /logo: `\$\{siteUrl\}\/icon-512\.png`/)
})

test('every client-only functional route is covered by the deployment matcher', () => {
  assert.match(staticRoutesSource, /FUNCTIONAL_SPA_PREFIXES[\s\S]*'\/account'[\s\S]*'\/checkout'[\s\S]*'\/unsubscribe'/)
})

test('web deployment routing is generated by the prerender build, not overridden by vercel.json', () => {
  const config = JSON.parse(readFileSync(new URL('../../apps/web/vercel.json', import.meta.url), 'utf8')) as Record<string, unknown>
  assert.equal(config.routes, undefined)
  assert.equal(config.rewrites, undefined)

  const prerender = readFileSync(new URL('../../apps/web/scripts/prerender.mjs', import.meta.url), 'utf8')
  assert.match(prerender, /status: 404/)
})

test('storefront and admin templates declare production favicon coverage', () => {
  for (const template of ['apps/web/index.html', 'apps/admin/index.html']) {
    const source = readFileSync(new URL(`../../${template}`, import.meta.url), 'utf8')
    assert.match(source, /favicon\.svg/)
    assert.match(source, /favicon-32x32\.png/)
    assert.match(source, /apple-touch-icon\.png/)
  }
})
